// 城市 → 国家(线索 6 与结算页用)。事实性元数据,与几何数据无关;
// 待管线扩展拉 POI 时迁入 public/cities/*.json。
export const COUNTRY: Record<string, { cn: string; en: string }> = {
  "new-york": { cn: "美国", en: "USA" },
  london: { cn: "英国", en: "UK" },
  "hong-kong": { cn: "中国", en: "China" },
  singapore: { cn: "新加坡", en: "Singapore" },
  tokyo: { cn: "日本", en: "Japan" },
  paris: { cn: "法国", en: "France" },
  venice: { cn: "意大利", en: "Italy" },
  barcelona: { cn: "西班牙", en: "Spain" },
  "washington-dc": { cn: "美国", en: "USA" },
  "san-francisco": { cn: "美国", en: "USA" },
  chicago: { cn: "美国", en: "USA" },
  amsterdam: { cn: "荷兰", en: "Netherlands" },
  istanbul: { cn: "土耳其", en: "Türkiye" },
  rome: { cn: "意大利", en: "Italy" },
  sydney: { cn: "澳大利亚", en: "Australia" },
  moscow: { cn: "俄罗斯", en: "Russia" },
  beijing: { cn: "中国", en: "China" },
  shanghai: { cn: "中国", en: "China" },
  bangkok: { cn: "泰国", en: "Thailand" },
  toronto: { cn: "加拿大", en: "Canada" },
  boston: { cn: "美国", en: "USA" },
  vienna: { cn: "奥地利", en: "Austria" },
  berlin: { cn: "德国", en: "Germany" },
  "buenos-aires": { cn: "阿根廷", en: "Argentina" },
  vancouver: { cn: "加拿大", en: "Canada" },
  lisbon: { cn: "葡萄牙", en: "Portugal" },
  kyoto: { cn: "日本", en: "Japan" },
  "rio-de-janeiro": { cn: "巴西", en: "Brazil" },
  mumbai: { cn: "印度", en: "India" },
  "cape-town": { cn: "南非", en: "South Africa" },
};
